import { env } from "~/env";
import { concatAssetWithIssuer } from "./utils";

export const ACTION_ISSUER =
  "GABHBO4IAEAKYODTIQC5G43MPD55BREA4P3MAXAMZKLEVQNF3S7PZFDU";

export const ACTION_ASSET_CODE = "ACTION";
export const HORIZON_URL = "https://horizon.stellar.org"; // Horizon server for pubnet

export const ASSETS: string[] = [
  concatAssetWithIssuer(ACTION_ASSET_CODE, ACTION_ISSUER),
];

export const DEFAULT_ASSET_LIMIT = "0.0000001";
export const DEFAULT_ASSET_PRICE = "1"; // XLM

export const STELLAR_URL = env.NEXT_PUBLIC_STELLAR_PUBNET
  ? "https://horizon.stellar.org"
  : "https://horizon-testnet.stellar.org";

export const STORAGE_SECRET = env.NEXT_PUBLIC_STELLAR_PUBNET
  ? "SCHZDTMCG376A7UOHAFEXW2SEEEW7TYVA6MSCJ25JH6W7O4CQ6LDHXDM"
  : "SDXDORIL2Y2ZOWPLOF6WYVK5A4OAJL22B3W7KDD2RBXYTKPAR3RYYYTM";

export const STORAGE_PUB = env.NEXT_PUBLIC_STELLAR_PUBNET
  ? "GDBUPMEXP6DKKS7HI4P6HNM5CUVM6WJF7SEH3GRXXH5TQ6XZQKYGIQKC"
  : "GD5UILGTWNRIWERORCB7YBLDRITMVP47QZ25UPYBJHHHHSM5AFE73HHB";

export const MOTHER_SECRET = env.NEXT_PUBLIC_STELLAR_PUBNET
  ? "SCVQYEUPGWX4YXIEDFTYXTJI6MA5Z564ATC5EPSLO3JPX7WIJ7SO2C3Q"
  : "SAUBVI5FGLDLJPCA3Q23Q77BVLGEYPM2G5CT4AQCS23W7VTBB3BUQD6R";
